# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Dev-Deployment

on:
  push:
    branches: [ "development","main" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        mini-app-id: ["2832578634743748881"]
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npx zmp-developer-token login ${{ secrets.ZALO_APP_ID }} ${{ secrets.ZALO_APP_SECRET }} ${{ secrets.ZALO_REFRESH_TOKEN }} >> $GITHUB_ENV
    - uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'ZALO_REFRESH_TOKEN'
        value: ${{ env.NEW_REFRESH_TOKEN }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - run: npm install
    - run: npm install -g zmp-cli
    - run: printf "\033[B\n$NEW_ACCESS_TOKEN" | APP_ID=${{ matrix.mini-app-id }} zmp login
    - run: |
        printf "\n$(git log -1 --pretty=%B)" | zmp deploy >> deploy-log.txt

    - name: Convert JS code to Bash
      run: |
        qrCode=$(echo $(cat deploy-log.txt) | sed -E 's/^(.*?)View app at:(.*?)\n//g')
        echo "$qrCode" >> $GITHUB_STEP_SUMMARY
        echo "$qrCode"
    
    - name: Report
      run: |
        echo "### Deployment success! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "View your deployment result: [Version Management](https://mini.zalo.me/miniapp/${{ secrets.ZALO_APP_ID }}/versions)" >> $GITHUB_STEP_SUMMARY
